### ISSUE TITLE
How to fix ann_LIBRARIES problem ?

### ISSUE THREAD

**Issue by dhiren-hamal** [FrankMoosmann/FranksVelodyneAlgos#2]
How to fix this problem?

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ann_LIBRARIES
    linked by target "TrackingUtils" in directory /home/dhiren/Dev/FranksVelodyneAlgos/libTrackingUtils
```
Thank you.

**Comment by dhiren-hamal** [comment]
Finally, I solved the problem
I had posted the problem on stackoverflow too. [link](https://stackoverflow.com/questions/58058572/cmake-compiler-error-ann-library-not-found)
My procedures are given follows:
1. First I tried to compile the source code in ubuntu 18.04 but got stuck with so many errors, so I tried in ubuntu 14.04 (docker).
2. I installed the required packages as the author mentioned.
3.  Now I stuck with ann_LIBRARIES problem, so for that, I downloaded ANN library from [link](https://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ann_1.1.2.tar.gz) and build by simply performing **make linux-g++** from inside ann_1.1.2 folder
4. Now ANN library is ready to use. After that to avoid the ann_LIBRARIES problem while building process, we should perform command from terminal `cmake -Dann_LIBRARIES=/home/ann_1.1.2/lib/libANN.a ..`
5. Now so far I build the project sucessfully. Now time to compile the code using `make` command, again I got `ANN/ANN.h: No such file or directory` error which I resolved by giving absulute path `#include </home/ann_1.1.2/include/ANN/ANN.h> //approximate) nearest neighbor` from each file where the error arose. Obviously providing absolute path is not a good idea. That's it

Hope this will help somebody. Thank you.

**Comment by firesnow1234** [comment]
`/home/jinxiao/YU/201910/FranksVelodyneAlgos-master/libTrackingUtils/TrackingUtils.cpp:6:55: fatal error: ANN/ANN.h: No such file or directory
compilation terminated.
libTrackingUtils/CMakeFiles/TrackingUtils.dir/build.make:350: recipe for target 'libTrackingUtils/CMakeFiles/TrackingUtils.dir/TrackingUtils.cpp.o' failed
make[2]: *** [libTrackingUtils/CMakeFiles/TrackingUtils.dir/TrackingUtils.cpp.o] Error 1
CMakeFiles/Makefile2:378: recipe for target 'libTrackingUtils/CMakeFiles/TrackingUtils.dir/all' failed
make[1]: *** [libTrackingUtils/CMakeFiles/TrackingUtils.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

After following your steps, I encountered this problem during compilation，how to solved it?
